### ISSUE TITLE
code incomplete

### ISSUE THREAD

**Issue by Zhang-Jiahui** [NeuralCarver/Michelangelo#15]
Hello,

when I try to use the codes provided, I find some files missing. For example, in the yaml, this file is not provided. "directgaussian.utils.trainings.lr_scheduler"

Below is some part of yaml file.
```
       scheduler:
        target: directgaussian.utils.trainings.lr_scheduler.LambdaWarmUpCosineFactorScheduler
        params:
          warm_up_steps: 5000
          f_start: 1.e-6
          f_min: 1.e-3
          f_max: 1.0
```

In addition, I find a variable is not defined, showed below:
https://github.com/NeuralCarver/Michelangelo/blob/main/michelangelo/models/asl_diffusion/clip_asl_diffuser_pl_module.py#L132
the learningrate is not defined.
